anchor_t: 3.0
box: 0.05
cls: 0.3
cls_pw: 6
copy_paste: 0.0
degrees: 10
fl_gamma: 0.0
fliplr: 0.5
flipud: 0.5
hsv_h: 0.1
hsv_s: 0.25
hsv_v: 0.25
iou_t: 0.4
lr0: 0.001
lrf: 0.01
mixup: 0.0
momentum: 0.937
mosaic: 1.0
obj: 0.7
obj_pw: 6
perspective: 0.0
scale: 0.5
shear: 0
translate: 0.0
warmup_bias_lr: 0.1
warmup_epochs: 3.0
warmup_momentum: 0.8
weight_decay: 0.0005
