1-PATHS:
  BACKGROUND_DIR: C:\ConceivableProjects\coc_follicular_h\ARDUCAM\bg
  PROJECT_DIR: C:\ConceivableProjects\coc_follicular_h\ARDUCAM
  WEIGHTS_DIR: C:\ConceivableProjects\coc_follicular_h\ARDUCAM\v1_1i\Weights\best.pt
  DETECT_DIR: C:\Users\PC KAIJU\ConceivableProjectsTools\FrameSampler\Sperm_in_needle-needle_tip\v1
2-PROJECT_CONFIG:
  BATCH_SIZE: 40
  DETECT: True 
  BG_DATA_DISTRIBUTION: .90
  CLASS_NAMES:
    0: coc
  EPOCHS: 250
  INNER_FOLDER_NAMES:
  - Weights
  - Config
  - Data
  PROJECT_NAME: v2_1
  TRAIN_DATA_DISTRIBUTION: 0.7
3-HYPS:
  lr0: 0.001  # initial learning rate (SGD=1E-2, Adam=1E-3)
  lrf: 0.01  # final OneCycleLR learning rate (lr0 * lrf)
  momentum: 0.937  # SGD momentum/Adam beta1
  weight_decay: 0.0005  # optimizer weight decay 5e-4
  warmup_epochs: 3.0  # warmup epochs (fractions ok)
  warmup_momentum: 0.8  # warmup initial momentum
  warmup_bias_lr: 0.1  # warmup initial bias lr
  box: 0.05  # box loss gain
  cls: 0.3  # cls loss gain
  cls_pw: 6  # cls BCELoss positive_weight
  obj: 0.7  # obj loss gain (scale with pixels)
  obj_pw: 6  # obj BCELoss positive_weight
  iou_t: 0.40  # IoU training threshold
  anchor_t: 3.0  # anchor-multiple threshold
  # anchors: 3  # anchors per output layer (0 to ignore)
  # this parameters are all zero since we want to use albumentation framework
  fl_gamma: 0.0  # focal loss gamma (efficientDet default gamma=1.5)
  hsv_h: 0.1  # image HSV-Hue augmentation (fraction)
  hsv_s: 0.25  # image HSV-Saturation augmentation (fraction)
  hsv_v: 0.25  # image HSV-Value augmentation (fraction)
  # hsv_h: 0.015  # image HSV-Hue augmentation (fraction)
  # hsv_s: 0.7  # image HSV-Saturation augmentation (fraction)
  # hsv_v: 0.4  # image HSV-Value augmentation (fraction)
  degrees: 10  # image rotation (+/- deg)
  translate: 0.0  # image translation (+/- fraction)
  scale: 0.5  # image scale (+/- gain)
  # scale: 1  # image scale (+/- gain)
  shear: 0  #image shear (+/- deg)
  perspective: 0.0  # image perspective (+/- fraction), range 0-0.001
  flipud: 0.5  # image flip up-down (probability)
  fliplr: 0.5  # image flip left-right (probability)
  mosaic: 1.0  # image mosaic (probability)
  mixup: 0.0  # image mixup (probability)
  copy_paste: 0.0  # segment copy-paste (probability)
